export * from './header/header.component'
export * from './body/body.component'
export * from './footer/footer.component'
export * from './question/question.component'
export * from './result/result.component'
